title: Macromedia Flash 8
description: В настоящее время Интернет занимает значительное место в жизни каждого человека. И что может быть привлекательнее, чем грамотно и красиво оформленная страница? Все больше и больше разработчиков в своих web-страницах используют flash-анимацию. Это может быть и реклама, так раздражающая некоторых пользователей, меню, достаточно продолжительные мультфильмы или даже обучающие приложения. В этом учебном курсе Вы научитесь обращаться с программой создания flash-анимации. Поверьте, это увлекательное, хотя порой и достаточно сложное занятие. 
theme: just-the-docs

url: https://Iliya5digital.github.io/Macromedia-Flash-8

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
